### ISSUE TITLE
die ?

### ISSUE THREAD

**Issue by davidnurdin** [clue/php-redis-server#23]
hi, 

it is a die project ? Or an alternative exist ? Thanks

**Comment by clue** [comment]
@davidnurdin Thank you for bringing this up!

This project is indeed somewhat dated at the moment, but there are in fact plans to resurrect this at some point in the future! I'm currently focusing my efforts on the larger @ReactPHP ecosystem, but will get back to this project as soon as time allows.

If you need this for a commercial project and/or you want to help sponsor this project, feel free to reach out and I'm happy to take a look!
